
services:

  challenge:
    image: nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - "./nginx-challenge.conf:/etc/nginx/nginx.conf:ro"
      - "./certbot/www/:/var/www/certbot/:ro"
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    platform: linux/amd64
    volumes:
      - "./certbot/:/etc/letsencrypt/:rw"
      - "./certbot/www/:/var/www/certbot/:rw"

  nginx:
    image: nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certbot/:/etc/nginx/ssl/:ro"
      - "./certbot/www/:/var/www/certbot/:ro"
    restart: unless-stopped

  personal:
    image: personal-v1:latest
    platform: linux/amd64
    ports:
      - "6969:6969"
    restart: unless-stopped
